[package]
name = "hive-llm"
edition.workspace = true
version.workspace = true

[dependencies]
hive-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
futures-util = { workspace = true }
eventsource-stream = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
