[package]
name = "hive-agent"
edition.workspace = true
version.workspace = true

[dependencies]
hive-core = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

# tools + swarm + vision live here now
inventory = { workspace = true }
reqwest = { workspace = true }
ignore = { workspace = true }
globset = { workspace = true }
regex = { workspace = true }
